<?xml version="1.0"?><!DOCTYPE routes [	<!ELEMENT routes (route*)>		<!ELEMENT route ( route_number, short_name, long_name)>			<!ELEMENT route_number (#PCDATA)>			<!ELEMENT short_name (#PCDATA)>			<!ELEMENT long_name (#PCDATA)>]>
<routes><route><route_number>0</route_number><short_name>Undefined</short_name><long_name></long_name></route><route><route_number>99</route_number><short_name>99 Deadhead</short_name><long_name>Deadhead</long_name></route><route><route_number>1</route_number><short_name>1  CROSSTOWN</short_name><long_name>CROSSTOWN</long_name></route><route><route_number>2</route_number><short_name>2  LAKE OTIS</short_name><long_name>LAKE OTIS</long_name></route><route><route_number>3</route_number><short_name>3  N LIGHTS</short_name><long_name>NORTHERN LIGHTS</long_name></route><route><route_number>7</route_number><short_name>7  SPENARD</short_name><long_name>SPENARD/AIRPORT</long_name></route><route><route_number>8</route_number><short_name>8  NORTHWAY</short_name><long_name>NORTHWAY</long_name></route><route><route_number>9</route_number><short_name>9  ARCTIC</short_name><long_name>ARCTIC</long_name></route><route><route_number>13</route_number><short_name>13 SR HOSP UAA</short_name><long_name>UNIVERSITY/HOSPITALS</long_name></route><route><route_number>14</route_number><short_name>14 GOVT HILL</short_name><long_name>GOVERNMENT HILL</long_name></route><route><route_number>15</route_number><short_name>15 DEBARR</short_name><long_name>15TH AVE/DEBARR</long_name></route><route><route_number>36</route_number><short_name>36 WEST ANCH</short_name><long_name>36TH AVE/WEST ANCHORAGE</long_name></route><route><route_number>45</route_number><short_name>45 MOUNTAIN VIE</short_name><long_name>MOUNTAIN VIEW</long_name></route><route><route_number>60</route_number><short_name>60 OLD SEWARD</short_name><long_name>OLD SEWARD</long_name></route><route><route_number>75</route_number><short_name>75 TUDOR</short_name><long_name>TUDOR</long_name></route><route><route_number>10</route_number><short_name>102 ER</short_name><long_name>EAGLE RIVER/CHUGIAK</long_name></route></routes>