<?xml version="1.0"?>
<!DOCTYPE stops [
<!ELEMENT stops (stop*)>
    <!ELEMENT stop (name, id, latitude, longitude)>
       <!ELEMENT name (#PCDATA)>
       <!ELEMENT id (#PCDATA)>
       <!ELEMENT latitude (#PCDATA)>
       <!ELEMENT longitude (#PCDATA)>
]>

<stops><stop><name>BAXTER and NORTHERN LIGHTS</name><id>1437</id><latitude>61.195278</latitude><longitude>-149.763412</longitude></stop><stop><name>LAKE OTIS and TUDOR</name><id>1438</id><latitude>61.180838</latitude><longitude>-149.838184</longitude></stop><stop><name>LAKE OTIS and ABBOTT</name><id>1439</id><latitude>61.137521</latitude><longitude>-149.834129</longitude></stop><stop><name>BENSON and C ST</name><id>1440</id><latitude>61.194252</latitude><longitude>-149.886739</longitude></stop><stop><name>NORTHERN LIGHTS and C ST</name><id>1441</id><latitude>61.195332</latitude><longitude>-149.886529</longitude></stop><stop><name>CENTENNIAL VILLAGE</name><id>1442</id><latitude>61.225349</latitude><longitude>-149.714437</longitude></stop><stop><name>NUNAKA and DEBARR</name><id>1443</id><latitude>61.209722</latitude><longitude>-149.770065</longitude></stop><stop><name>PATTERSON and NORTHERN LIGHTS</name><id>1444</id><latitude>61.19527</latitude><longitude>-149.748436</longitude></stop><stop><name>SPENARD and NORTHERN LIGHTS</name><id>1445</id><latitude>61.195297</latitude><longitude>-149.905442</longitude></stop><stop><name>NORTHWOOD and 88TH AVE</name><id>1446</id><latitude>61.141098</latitude><longitude>-149.921991</longitude></stop><stop><name>JEWEL LAKE and 88TH AVE</name><id>1447</id><latitude>61.141088</latitude><longitude>-149.951885</longitude></stop><stop><name>AIRPORT SOUTH TERMINAL</name><id>1448</id><latitude>61.173144</latitude><longitude>-149.979292</longitude></stop><stop><name>BONIFACE and 4TH AVE</name><id>1449</id><latitude>61.218677</latitude><longitude>-149.778393</longitude></stop><stop><name>OKLAHOMA and BOUNDARY</name><id>1450</id><latitude>61.224178</latitude><longitude>-149.744783</longitude></stop><stop><name>ARCTIC and INTL AIRPORT RD</name><id>1451</id><latitude>61.173637</latitude><longitude>-149.897948</longitude></stop><stop><name>SENIOR CENTER</name><id>1452</id><latitude>61.20352</latitude><longitude>-149.858495</longitude></stop><stop><name>NORTHERN LIGHTS and BONIFACE</name><id>1453</id><latitude>61.195249</latitude><longitude>-149.778373</longitude></stop><stop><name>13TH and GAMBELL</name><id>1454</id><latitude>61.209681</latitude><longitude>-149.871035</longitude></stop><stop><name>BLUFF and BIRCH</name><id>1455</id><latitude>61.230949</latitude><longitude>-149.870173</longitude></stop><stop><name>HOLLYWOOD and LOOP</name><id>1456</id><latitude>61.230365</latitude><longitude>-149.874384</longitude></stop><stop><name>ALASKA REGIONAL HOSPITAL</name><id>1457</id><latitude>61.210217</latitude><longitude>-149.826379</longitude></stop><stop><name>MINNESOTA and N LIGHTS</name><id>1458</id><latitude>61.195298</latitude><longitude>-149.91309</longitude></stop><stop><name>SPENARD and WISCONSIN</name><id>1459</id><latitude>61.179243</latitude><longitude>-149.938883</longitude></stop><stop><name>TUDOR and MINNESOTA</name><id>1460</id><latitude>61.180774</latitude><longitude>-149.913285</longitude></stop><stop><name>36TH AVE and A STREET</name><id>1461</id><latitude>61.188075</latitude><longitude>-149.883124</longitude></stop><stop><name>ALASKA PACIFIC UNIVERSITY</name><id>1462</id><latitude>61.191014</latitude><longitude>-149.803076</longitude></stop><stop><name>BRAGAW and MT. VIEW</name><id>1463</id><latitude>61.22415</latitude><longitude>-149.80839</longitude></stop><stop><name>PENLAND and NORTHWAY</name><id>1464</id><latitude>61.215687</latitude><longitude>-149.812657</longitude></stop><stop><name>NORTHERN LIGHTS and BRAGAW</name><id>1465</id><latitude>61.19887</latitude><longitude>-149.808338</longitude></stop><stop><name>DENALI and BENSON</name><id>1467</id><latitude>61.193481</latitude><longitude>-149.876679</longitude></stop><stop><name>OLD SEWARD and TUDOR</name><id>1468</id><latitude>61.180797</latitude><longitude>-149.868157</longitude></stop><stop><name>OCEANVIEW and JOHNS</name><id>1469</id><latitude>61.103743</latitude><longitude>-149.877534</longitude></stop><stop><name>HUFFMAN BUSINESS PARK</name><id>1470</id><latitude>61.110207</latitude><longitude>-149.857457</longitude></stop><stop><name>TUDOR and ELMORE</name><id>1471</id><latitude>61.180836</latitude><longitude>-149.808278</longitude></stop><stop><name>MULDOON and DEBARR EAST</name><id>1473</id><latitude>61.210862</latitude><longitude>-149.733229</longitude></stop><stop><name>MULDOON and DEBARR WEST</name><id>1474</id><latitude>61.209295</latitude><longitude>-149.733821</longitude></stop><stop><name>DOWNTOWN TRANSIT CENTER</name><id>1477</id><latitude>61.216552</latitude><longitude>-149.896764</longitude></stop><stop><name>A STREET and 36TH AVE</name><id>1478</id><latitude>61.188075</latitude><longitude>-149.883126</longitude></stop><stop><name>C STREET and 36TH AVE</name><id>1479</id><latitude>61.188073</latitude><longitude>-149.886595</longitude></stop><stop><name>AK NATIVE MEDICAL CENTER</name><id>1481</id><latitude>61.181944</latitude><longitude>-149.801485</longitude></stop><stop><name>BONIFACE INTERCHANGE</name><id>1482</id><latitude>61.223304</latitude><longitude>-149.777365</longitude></stop><stop><name>NORTH BIRCHWOOD PARK and RIDE</name><id>1487</id><latitude>61.402892</latitude><longitude>-149.468106</longitude></stop><stop><name>EAGLE RIVER TRANSIT CENTER</name><id>1490</id><latitude>61.327765</latitude><longitude>-149.573676</longitude></stop><stop><name>LAKE OTIS and DOWLING</name><id>1492</id><latitude>61.166405</latitude><longitude>-149.838142</longitude></stop><stop><name>DIMOND TRANSIT CENTER</name><id>1494</id><latitude>61.142763</latitude><longitude>-149.871953</longitude></stop><stop><name>TUDOR GARAGE</name><id>1495</id><latitude>61.177371</latitude><longitude>-149.814004</longitude></stop><stop><name>BASE 3650 Tudor Road</name><id>1496</id><latitude>0.0</latitude><longitude>0.0</longitude></stop><stop><name>C STREET and 7TH AVENUE SSW</name><id>1498</id><latitude>61.215198</latitude><longitude>-149.887511</longitude></stop><stop><name>C STREET and 10TH AVENUE SSW: 0004</name><id>1499</id><latitude>61.212406</latitude><longitude>-149.887517</longitude></stop><stop><name>C STREET and 12TH AVENUE SSW: 0005</name><id>1500</id><latitude>61.210296</latitude><longitude>-149.887483</longitude></stop><stop><name>C STREET and 14TH AVENUE NNW: 0006</name><id>1501</id><latitude>61.208679</latitude><longitude>-149.887493</longitude></stop><stop><name>C STREET and 16TH AVENUE SSW: 0007</name><id>1502</id><latitude>61.205769</latitude><longitude>-149.887535</longitude></stop><stop><name>C STREET and 19TH AVENUE NNW: 0008</name><id>1503</id><latitude>61.203688</latitude><longitude>-149.887627</longitude></stop><stop><name>C STREET and 22ND AVENUE NNW: 0009</name><id>1504</id><latitude>61.200839</latitude><longitude>-149.887529</longitude></stop><stop><name>C STREET and FIREWEED SSW: 0010</name><id>1505</id><latitude>61.197746</latitude><longitude>-149.88703</longitude></stop><stop><name>C STREET and BENSON NNW: 0011</name><id>1506</id><latitude>61.194451</latitude><longitude>-149.886782</longitude></stop><stop><name>C STREET and 31ST AVENUE NNW: 0012</name><id>1507</id><latitude>61.192709</latitude><longitude>-149.886782</longitude></stop><stop><name>36TH AVENUE and C STREET ESE: 0014</name><id>1508</id><latitude>61.187996</latitude><longitude>-149.885213</longitude></stop><stop><name>36TH AVENUE and A STREET ESE</name><id>1509</id><latitude>61.187957</latitude><longitude>-149.88181</longitude></stop><stop><name>36TH AVENUE and DENALI WSW: 0016</name><id>1510</id><latitude>61.187984</latitude><longitude>-149.877381</longitude></stop><stop><name>36TH AVENUE and OLD SEWARD WSW: 0017</name><id>1511</id><latitude>61.187998</latitude><longitude>-149.869001</longitude></stop><stop><name>36TH AVENUE and NEW SEWARD ESE: 0018</name><id>1512</id><latitude>61.187973</latitude><longitude>-149.862833</longitude></stop><stop><name>36TH AVENUE and LATOUCHE WSW</name><id>1513</id><latitude>61.18799</latitude><longitude>-149.859445</longitude></stop><stop><name>36TH AVENUE and LOCARNO ESE</name><id>1514</id><latitude>61.188013</latitude><longitude>-149.855386</longitude></stop><stop><name>36TH AVENUE and MACINNES ESE</name><id>1515</id><latitude>61.187949</latitude><longitude>-149.848835</longitude></stop><stop><name>LAKE OTIS and 36TH AVENUE SSW: 0023</name><id>1517</id><latitude>61.187323</latitude><longitude>-149.83846</longitude></stop><stop><name>LAKE OTIS and 38TH AVENUE SSW: 0024</name><id>1518</id><latitude>61.185757</latitude><longitude>-149.83838</longitude></stop><stop><name>LAKE OTIS and 42ND AVENUE NNW: 0025</name><id>1519</id><latitude>61.182748</latitude><longitude>-149.838371</longitude></stop><stop><name>LAKE OTIS and TUDOR SSW: 0026</name><id>1520</id><latitude>61.179662</latitude><longitude>-149.838406</longitude></stop><stop><name>LAKE OTIS and HOMESTEAD SSW</name><id>1521</id><latitude>61.177152</latitude><longitude>-149.838369</longitude></stop><stop><name>LAKE OTIS and WALDRON SSW</name><id>1522</id><latitude>61.174402</latitude><longitude>-149.838394</longitude></stop><stop><name>LAKE OTIS and 54TH AVENUE SSW: 0029</name><id>1523</id><latitude>61.171576</latitude><longitude>-149.838336</longitude></stop><stop><name>LAKE OTIS and PAGO PAGO NNW</name><id>1524</id><latitude>61.168863</latitude><longitude>-149.838404</longitude></stop><stop><name>LAKE OTIS and DOWLING SSW: 0031</name><id>1525</id><latitude>61.165865</latitude><longitude>-149.838429</longitude></stop><stop><name>LAKE OTIS and 63RD AVENUE SSW: 0032</name><id>1526</id><latitude>61.163456</latitude><longitude>-149.835964</longitude></stop><stop><name>LAKE OTIS and 68TH AVENUE SSW: 0033</name><id>1527</id><latitude>61.158822</latitude><longitude>-149.83445</longitude></stop><stop><name>LAKE OTIS and 72ND AVENUE SSW: 0034</name><id>1528</id><latitude>61.155016</latitude><longitude>-149.83444</longitude></stop><stop><name>LAKE OTIS and LORE SSW: 0035</name><id>1529</id><latitude>61.151457</latitude><longitude>-149.834421</longitude></stop><stop><name>LAKE OTIS and 80TH AVENUE SSW: 0036</name><id>1530</id><latitude>61.147558</latitude><longitude>-149.834409</longitude></stop><stop><name>LAKE OTIS and 85TH AVENUE NNW: 0037</name><id>1531</id><latitude>61.14402</latitude><longitude>-149.834352</longitude></stop><stop><name>LAKE OTIS and 88TH AVENUE SSW: 0038</name><id>1532</id><latitude>61.140782</latitude><longitude>-149.834389</longitude></stop><stop><name>INDEPENDENCE and SENTRY NNW: 0043</name><id>1533</id><latitude>61.134677</latitude><longitude>-149.841718</longitude></stop><stop><name>INDEPENDENCE and VANGUARD SSW: 0044</name><id>1534</id><latitude>61.131886</latitude><longitude>-149.845513</longitude></stop><stop><name>INDEPENDENCE and COLONY SSW: 0045</name><id>1535</id><latitude>61.13033</latitude><longitude>-149.845923</longitude></stop><stop><name>JAMESTOWN and INDEPENDENCE SSW</name><id>1536</id><latitude>61.128539</latitude><longitude>-149.845619</longitude></stop><stop><name>JAMESTOWN and MRTHAS VNYRD NNW: 0047</name><id>1537</id><latitude>61.127568</latitude><longitude>-149.847048</longitude></stop><stop><name>JAMESTOWN and ELCADORE SSW: 0048</name><id>1538</id><latitude>61.12522</latitude><longitude>-149.848114</longitude></stop><stop><name>COMMODORE and ELCADORE NNW: 0049</name><id>1539</id><latitude>61.123773</latitude><longitude>-149.851073</longitude></stop><stop><name>OMALLEY and BRAYTON WNW: 0050</name><id>1540</id><latitude>61.123211</latitude><longitude>-149.856079</longitude></stop><stop><name>OLD SEWARD and OMALLEY NNE: 0051</name><id>1541</id><latitude>61.123594</latitude><longitude>-149.863409</longitude></stop><stop><name>OLD SEWARD and LINGON BERRY SSE</name><id>1542</id><latitude>61.127701</latitude><longitude>-149.863708</longitude></stop><stop><name>OLD SEWARD and SUNDOWN SSE</name><id>1543</id><latitude>61.132638</latitude><longitude>-149.863711</longitude></stop><stop><name>OLD SEWARD and SCOOTER NNE</name><id>1544</id><latitude>61.137899</latitude><longitude>-149.863756</longitude></stop><stop><name>OLD SEWARD and SUNDOWN NNW</name><id>1545</id><latitude>61.133328</latitude><longitude>-149.864252</longitude></stop><stop><name>OLD SEWARD and ABBOTT SSW</name><id>1546</id><latitude>61.136813</latitude><longitude>-149.864298</longitude></stop><stop><name>OLD SEWARD and LAKEWOOD NNW</name><id>1547</id><latitude>61.134618</latitude><longitude>-149.864169</longitude></stop><stop><name>OLD SEWARD and 100TH AVE SSW</name><id>1548</id><latitude>61.129561</latitude><longitude>-149.864178</longitude></stop><stop><name>OLD SEWARD and LINGON BERRY SSW: 0064</name><id>1549</id><latitude>61.127452</latitude><longitude>-149.864138</longitude></stop><stop><name>OMALLEY and OMALLEY CTR WSW: 0065</name><id>1550</id><latitude>61.122971</latitude><longitude>-149.860896</longitude></stop><stop><name>COMMODORE and ELCADORE NNE: 0066</name><id>1551</id><latitude>61.123771</latitude><longitude>-149.850714</longitude></stop><stop><name>JAMESTOWN and COMMODORE NNE</name><id>1552</id><latitude>61.126289</latitude><longitude>-149.847875</longitude></stop><stop><name>JAMESTOWN and MRTHAS VNYRD NNE</name><id>1553</id><latitude>61.127572</latitude><longitude>-149.846782</longitude></stop><stop><name>INDEPENDENCE and JAMESTOWN WNW: 0069</name><id>1554</id><latitude>61.129296</latitude><longitude>-149.84526</longitude></stop><stop><name>INDEPENDENCE and COLONY NNE: 0070</name><id>1555</id><latitude>61.131217</latitude><longitude>-149.845694</longitude></stop><stop><name>INDEPENDENCE and VANGUARD NNE: 0071</name><id>1556</id><latitude>61.132679</latitude><longitude>-149.844028</longitude></stop><stop><name>INDEPENDENCE and SENTRY SSE: 0072</name><id>1557</id><latitude>61.133822</latitude><longitude>-149.841702</longitude></stop><stop><name>LAKE OTIS and ABBOTT NNE: 0075</name><id>1558</id><latitude>61.138063</latitude><longitude>-149.833851</longitude></stop><stop><name>LAKE OTIS and 88TH AVENUE NNE: 0076</name><id>1559</id><latitude>61.141626</latitude><longitude>-149.83388</longitude></stop><stop><name>LAKE OTIS and 84TH AVENUE SSE</name><id>1560</id><latitude>61.143452</latitude><longitude>-149.833844</longitude></stop><stop><name>LAKE OTIS and 80TH AVENUE SSE: 0078</name><id>1561</id><latitude>61.14801</latitude><longitude>-149.833924</longitude></stop><stop><name>LAKE OTIS and LORE NNE: 0079</name><id>1562</id><latitude>61.152491</latitude><longitude>-149.833936</longitude></stop><stop><name>LAKE OTIS and 72ND AVENUE NNE: 0080</name><id>1563</id><latitude>61.156034</latitude><longitude>-149.833987</longitude></stop><stop><name>LAKE OTIS and 68TH AVENUE NNE: 0081</name><id>1564</id><latitude>61.159673</latitude><longitude>-149.833995</longitude></stop><stop><name>LAKE OTIS and 63RD AVENUE SSE: 0082</name><id>1565</id><latitude>61.163002</latitude><longitude>-149.834732</longitude></stop><stop><name>LAKE OTIS and DOWLING NNE: 0083</name><id>1566</id><latitude>61.167108</latitude><longitude>-149.837928</longitude></stop><stop><name>LAKE OTIS and PAGO PAGO NNE: 0084</name><id>1567</id><latitude>61.168973</latitude><longitude>-149.837983</longitude></stop><stop><name>LAKE OTIS and YMCA E: 0085</name><id>1568</id><latitude>61.172119</latitude><longitude>-149.83799</longitude></stop><stop><name>LAKE OTIS and WALDRON NNE: 0086</name><id>1569</id><latitude>61.175672</latitude><longitude>-149.837926</longitude></stop><stop><name>LAKE OTIS and 48TH AVENUE NNE: 0087</name><id>1570</id><latitude>61.178335</latitude><longitude>-149.837896</longitude></stop><stop><name>LAKE OTIS and TUDOR NNE: 0088</name><id>1571</id><latitude>61.181574</latitude><longitude>-149.83782</longitude></stop><stop><name>LAKE OTIS and 42ND AVENUE NNE: 0089</name><id>1572</id><latitude>61.183027</latitude><longitude>-149.83801</longitude></stop><stop><name>LAKE OTIS and 40TH AVENUE NNE: 0090</name><id>1573</id><latitude>61.18525</latitude><longitude>-149.837934</longitude></stop><stop><name>36TH AVENUE and LAKE OTIS WNW: 0091</name><id>1574</id><latitude>61.188133</latitude><longitude>-149.838994</longitude></stop><stop><name>36TH AVENUE and MACINNES WNW: 0093</name><id>1576</id><latitude>61.188129</latitude><longitude>-149.850219</longitude></stop><stop><name>36TH AVENUE and LATOUCHE WNW</name><id>1577</id><latitude>61.188196</latitude><longitude>-149.859491</longitude></stop><stop><name>36TH AVENUE and DENALI WNW</name><id>1578</id><latitude>61.188196</latitude><longitude>-149.878194</longitude></stop><stop><name>A STREET and 36TH AVENUE NNE</name><id>1579</id><latitude>61.188891</latitude><longitude>-149.882825</longitude></stop><stop><name>A STREET and 31ST AVENUE SSE: 0100</name><id>1580</id><latitude>61.192401</latitude><longitude>-149.882929</longitude></stop><stop><name>A STREET and NORTHERN LIGHTS NNE: 0101</name><id>1581</id><latitude>61.195933</latitude><longitude>-149.882935</longitude></stop><stop><name>A STREET and FIREWEED NNE: 0102</name><id>1582</id><latitude>61.199169</latitude><longitude>-149.882806</longitude></stop><stop><name>A STREET and CHESTER CREEK TRAIL: 0103</name><id>1583</id><latitude>61.204353</latitude><longitude>-149.883145</longitude></stop><stop><name>A STREET and 16TH AVENUE NNE: 0104</name><id>1584</id><latitude>61.206829</latitude><longitude>-149.882898</longitude></stop><stop><name>A STREET and 13TH AVENUE NNE: 0105</name><id>1585</id><latitude>61.210194</latitude><longitude>-149.883095</longitude></stop><stop><name>A STREET and 11TH AVENUE NNE: 0106</name><id>1586</id><latitude>61.212138</latitude><longitude>-149.883276</longitude></stop><stop><name>SPENARD and 25TH AVENUE SSW: 0127</name><id>1587</id><latitude>61.197572</latitude><longitude>-149.905568</longitude></stop><stop><name>SPENARD and 27TH AVENUE SSW: 0128</name><id>1588</id><latitude>61.196082</latitude><longitude>-149.905579</longitude></stop><stop><name>SPENARD and BENSON NNW</name><id>1589</id><latitude>61.194436</latitude><longitude>-149.905635</longitude></stop><stop><name>SPENARD and 30TH AVENUE NNW</name><id>1590</id><latitude>61.19314</latitude><longitude>-149.905568</longitude></stop><stop><name>SPENARD and 33RD AVENUE NNW: 0131</name><id>1591</id><latitude>61.190675</latitude><longitude>-149.907481</longitude></stop><stop><name>SPENARD and 34TH AVENUE SSW: 0132</name><id>1592</id><latitude>61.189041</latitude><longitude>-149.908677</longitude></stop><stop><name>SPENARD and MINNESOTA ENE: 0133</name><id>1593</id><latitude>61.186983</latitude><longitude>-149.912189</longitude></stop><stop><name>SPENARD and GREENLAND WNW</name><id>1594</id><latitude>61.186666</latitude><longitude>-149.914835</longitude></stop><stop><name>SPENARD and OREGON WNW</name><id>1595</id><latitude>61.186077</latitude><longitude>-149.918527</longitude></stop><stop><name>SPENARD and MCRAE WNW</name><id>1596</id><latitude>61.185174</latitude><longitude>-149.923969</longitude></stop><stop><name>SPENARD and NORTHWOOD ENE: 0137</name><id>1597</id><latitude>61.183869</latitude><longitude>-149.927104</longitude></stop><stop><name>SPENARD and WISCONSIN SSW: 0141</name><id>1598</id><latitude>61.178721</latitude><longitude>-149.939617</longitude></stop><stop><name>SPENARD and BREEZEWOOD SSW</name><id>1599</id><latitude>61.17706</latitude><longitude>-149.942041</longitude></stop><stop><name>SPENARD and INTL ARPT RD NNW: 0143</name><id>1600</id><latitude>61.175228</latitude><longitude>-149.944283</longitude></stop><stop><name>JEWEL LAKE and INTL ARPT RD SSW</name><id>1601</id><latitude>61.173263</latitude><longitude>-149.943415</longitude></stop><stop><name>COLLINS WAY and JEWEL LAKE SSW</name><id>1602</id><latitude>61.166323</latitude><longitude>-149.942789</longitude></stop><stop><name>COLLINS WAY and 62ND AVENUE NNW</name><id>1603</id><latitude>61.164602</latitude><longitude>-149.94039</longitude></stop><stop><name>64TH AVENUE and COLLINS WAY ESE</name><id>1604</id><latitude>61.162725</latitude><longitude>-149.938009</longitude></stop><stop><name>CRANBERRY and HOLLY SSW</name><id>1605</id><latitude>61.160776</latitude><longitude>-149.936982</longitude></stop><stop><name>RASPBERRY and CRANBERRY WNW</name><id>1606</id><latitude>61.159471</latitude><longitude>-149.937835</longitude></stop><stop><name>RASPBERRY and BLACKBERRY WNW: 0151</name><id>1607</id><latitude>61.159343</latitude><longitude>-149.945456</longitude></stop><stop><name>JEWEL LAKE and RASPBERRY SSW: 0154</name><id>1608</id><latitude>61.158084</latitude><longitude>-149.95201</longitude></stop><stop><name>JEWEL LAKE and 74TH AVENUE NNW</name><id>1609</id><latitude>61.15393</latitude><longitude>-149.952108</longitude></stop><stop><name>JEWEL LAKE and STRAWBERRY SSW</name><id>1610</id><latitude>61.151514</latitude><longitude>-149.952125</longitude></stop><stop><name>JEWEL LAKE and 79TH COURT SSW</name><id>1611</id><latitude>61.149322</latitude><longitude>-149.952135</longitude></stop><stop><name>JEWEL LAKE and 82ND AVENUE NNW</name><id>1612</id><latitude>61.146887</latitude><longitude>-149.95212</longitude></stop><stop><name>JEWEL LAKE and 84TH AVENUE NNW</name><id>1613</id><latitude>61.144943</latitude><longitude>-149.952091</longitude></stop><stop><name>88TH AVENUE and JEWEL LAKE ESE: 0162</name><id>1614</id><latitude>61.141015</latitude><longitude>-149.949989</longitude></stop><stop><name>88TH AVENUE and ALAMOSA ESE</name><id>1615</id><latitude>61.141001</latitude><longitude>-149.945966</longitude></stop><stop><name>88TH AVENUE and DEWBERRY ESE</name><id>1616</id><latitude>61.141004</latitude><longitude>-149.939802</longitude></stop><stop><name>88TH AVENUE and CRANBERRY ESE</name><id>1617</id><latitude>61.14099</latitude><longitude>-149.936335</longitude></stop><stop><name>88TH AVENUE and FOREST VILLAGE ESE</name><id>1618</id><latitude>61.141014</latitude><longitude>-149.933041</longitude></stop><stop><name>ARLENE and DIMOND NNW</name><id>1619</id><latitude>61.138588</latitude><longitude>-149.929558</longitude></stop><stop><name>DIMOND and VICTOR ESE</name><id>1620</id><latitude>61.137289</latitude><longitude>-149.919427</longitude></stop><stop><name>DIMOND and MINNESOTA ESE: 0179</name><id>1621</id><latitude>61.140868</latitude><longitude>-149.905249</longitude></stop><stop><name>DIMOND and ANGELA ESE: 0180</name><id>1622</id><latitude>61.13814</latitude><longitude>-149.914884</longitude></stop><stop><name>DIMOND and DIMOND CTR DR WNW: 0189</name><id>1623</id><latitude>61.144916</latitude><longitude>-149.872669</longitude></stop><stop><name>DIMOND and C STREET WNW: 0191</name><id>1624</id><latitude>61.144911</latitude><longitude>-149.888768</longitude></stop><stop><name>DIMOND and MINNESOTA ENE: 0193</name><id>1625</id><latitude>61.141256</latitude><longitude>-149.905399</longitude></stop><stop><name>DIMOND and ANGELA ENE</name><id>1626</id><latitude>61.138486</latitude><longitude>-149.914901</longitude></stop><stop><name>DIMOND and VICTOR WNW: 0195</name><id>1627</id><latitude>61.137655</latitude><longitude>-149.923468</longitude></stop><stop><name>88TH AVENUE and FOREST VILLAGE ENE</name><id>1629</id><latitude>61.141171</latitude><longitude>-149.933427</longitude></stop><stop><name>88TH AVENUE and CRANBERRY WNW: 0199</name><id>1630</id><latitude>61.141153</latitude><longitude>-149.937753</longitude></stop><stop><name>88TH AVENUE and DEWBERRY WNW</name><id>1631</id><latitude>61.141173</latitude><longitude>-149.941195</longitude></stop><stop><name>88TH AVENUE and ALAMOSA WNW</name><id>1632</id><latitude>61.141168</latitude><longitude>-149.946425</longitude></stop><stop><name>88TH AVENUE and MOLANARY WNW</name><id>1633</id><latitude>61.141166</latitude><longitude>-149.949424</longitude></stop><stop><name>JEWEL LAKE and 88TH AVENUE NNE: 0210</name><id>1634</id><latitude>61.141705</latitude><longitude>-149.951684</longitude></stop><stop><name>JEWEL LAKE and 84TH AVENUE SSE</name><id>1635</id><latitude>61.144388</latitude><longitude>-149.951656</longitude></stop><stop><name>JEWEL LAKE and 82ND AVENUE NNE: 0213</name><id>1636</id><latitude>61.146968</latitude><longitude>-149.951743</longitude></stop><stop><name>JEWEL LAKE and 79TH AVENUE SSE</name><id>1637</id><latitude>61.148989</latitude><longitude>-149.951705</longitude></stop><stop><name>JEWEL LAKE and STRAWBERRY NNE</name><id>1638</id><latitude>61.152487</latitude><longitude>-149.951629</longitude></stop><stop><name>JEWEL LAKE and 74TH AVENUE NNE</name><id>1639</id><latitude>61.154354</latitude><longitude>-149.951595</longitude></stop><stop><name>JEWEL LAKE and WEIMER NNE: 0217</name><id>1640</id><latitude>61.156645</latitude><longitude>-149.951648</longitude></stop><stop><name>RASPBERRY and JEWEL LAKE ESE: 0218</name><id>1641</id><latitude>61.159048</latitude><longitude>-149.950401</longitude></stop><stop><name>RASPBERRY and CHEVIGNY ESE</name><id>1642</id><latitude>61.15907</latitude><longitude>-149.945903</longitude></stop><stop><name>RASPBERRY and CRANBERRY WSW</name><id>1643</id><latitude>61.159055</latitude><longitude>-149.941101</longitude></stop><stop><name>CRANBERRY and 65TH AVENUE SSE</name><id>1644</id><latitude>61.161314</latitude><longitude>-149.936765</longitude></stop><stop><name>64TH AVENUE and COLLINS WAY ENE: 0223</name><id>1645</id><latitude>61.162801</latitude><longitude>-149.938341</longitude></stop><stop><name>COLLINS WAY and 62ND AVENUE NNE</name><id>1646</id><latitude>61.164686</latitude><longitude>-149.940259</longitude></stop><stop><name>COLLINS WAY and JEWEL LAKE SSE: 0225</name><id>1647</id><latitude>61.166285</latitude><longitude>-149.942512</longitude></stop><stop><name>JEWEL LAKE and INTL ARPT RD SSE</name><id>1648</id><latitude>61.173339</latitude><longitude>-149.942827</longitude></stop><stop><name>SPENARD and INTL ARPT RD NNE: 0227</name><id>1649</id><latitude>61.175119</latitude><longitude>-149.943772</longitude></stop><stop><name>SPENARD and VALLEYWOOD NNE</name><id>1650</id><latitude>61.177653</latitude><longitude>-149.940313</longitude></stop><stop><name>SPENARD and WISCONSIN NNE</name><id>1651</id><latitude>61.17959</latitude><longitude>-149.938265</longitude></stop><stop><name>SPENARD and MCKINLEY SSE: 0232</name><id>1652</id><latitude>61.183983</latitude><longitude>-149.926171</longitude></stop><stop><name>SPENARD and TAFT ESE</name><id>1653</id><latitude>61.185366</latitude><longitude>-149.922413</longitude></stop><stop><name>SPENARD and WYOMING WSW: 0234</name><id>1654</id><latitude>61.186326</latitude><longitude>-149.916088</longitude></stop><stop><name>SPENARD and MINNESOTA ESE</name><id>1655</id><latitude>61.186842</latitude><longitude>-149.911704</longitude></stop><stop><name>SPENARD and 36TH AVENUE NNE</name><id>1656</id><latitude>61.18847</latitude><longitude>-149.908449</longitude></stop><stop><name>SPENARD and 33RD AVENUE NNE: 0237</name><id>1657</id><latitude>61.191292</latitude><longitude>-149.906626</longitude></stop><stop><name>SPENARD and Benson Blvd SSE</name><id>1658</id><latitude>61.193564</latitude><longitude>-149.90529</longitude></stop><stop><name>SPENARD and NORTHERN LIGHTS NNE: 0239</name><id>1659</id><latitude>61.195857</latitude><longitude>-149.905287</longitude></stop><stop><name>SPENARD and 26TH AVE NNE</name><id>1660</id><latitude>61.197395</latitude><longitude>-149.905242</longitude></stop><stop><name>17TH AVENUE and E STREET WSW</name><id>1661</id><latitude>61.205181</latitude><longitude>-149.89271</longitude></stop><stop><name>A STREET and 8TH AVENUE NNE: 0250</name><id>1662</id><latitude>61.215023</latitude><longitude>-149.883118</longitude></stop><stop><name>BENSON and SPENARD ESE: 0275</name><id>1663</id><latitude>61.193942</latitude><longitude>-149.904487</longitude></stop><stop><name>BENSON and ARCTIC ESE: 0276</name><id>1664</id><latitude>61.194138</latitude><longitude>-149.896939</longitude></stop><stop><name>BENSON and CHEECHAKO ESE: 0277</name><id>1665</id><latitude>61.194175</latitude><longitude>-149.893564</longitude></stop><stop><name>BENSON and EUREKA ESE: 0278</name><id>1666</id><latitude>61.194167</latitude><longitude>-149.889929</longitude></stop><stop><name>BENSON and C STREET ESE: 0279</name><id>1667</id><latitude>61.194147</latitude><longitude>-149.88568</longitude></stop><stop><name>BENSON and A STREET ESE: 0280</name><id>1668</id><latitude>61.19369</latitude><longitude>-149.879827</longitude></stop><stop><name>BENSON and DENALI ESE</name><id>1669</id><latitude>61.193312</latitude><longitude>-149.875134</longitude></stop><stop><name>BENSON and NEW SEWARD ESE: 0282</name><id>1670</id><latitude>61.193322</latitude><longitude>-149.866474</longitude></stop><stop><name>BENSON and LATOUCHE ESE: 0283</name><id>1671</id><latitude>61.194516</latitude><longitude>-149.85976</longitude></stop><stop><name>NORTHERN LIGHTS and REDWOOD ESE: 0284</name><id>1672</id><latitude>61.195305</latitude><longitude>-149.855217</longitude></stop><stop><name>NORTHERN LIGHTS and DRAKE WSW: 0285</name><id>1673</id><latitude>61.195223</latitude><longitude>-149.846588</longitude></stop><stop><name>NORTHERN LIGHTS and LAKE OTIS WSW: 0286</name><id>1674</id><latitude>61.195219</latitude><longitude>-149.842519</longitude></stop><stop><name>PROVIDENCE and PIPER ESE</name><id>1675</id><latitude>61.187884</latitude><longitude>-149.827836</longitude></stop><stop><name>UAA DRIVE and PROVIDENCE NNE</name><id>1676</id><latitude>61.190267</latitude><longitude>-149.82235</longitude></stop><stop><name>BONIFACE and NORTHERN LIGHTS NNE: 0302</name><id>1677</id><latitude>61.195917</latitude><longitude>-149.778172</longitude></stop><stop><name>BONIFACE and 24TH AVENUE SSE: 0303</name><id>1678</id><latitude>61.198302</latitude><longitude>-149.778171</longitude></stop><stop><name>PEMBROKE and COLLEGE SSE: 0304</name><id>1679</id><latitude>61.200347</latitude><longitude>-149.777904</longitude></stop><sto