<?xml version="1.0"?>
<!DOCTYPE vehicle-locations [
<!ELEMENT vehicle-locations (report-generated, vehicle*)>
	<!ELEMENT report-generated (#PCDATA)>
		<!-- timezone is an integer between -12 and 12 inclusive. -->
       <!-- the timezone is reference to GMT and is -5 for Acadia. -->
		<!ATTLIST report-generated timezone CDATA #REQUIRED>
	<!ELEMENT vehicle (name, routeid, tripid, runid*, destination*, direction, laststop, latitude, longitude, speed, heading)>
		<!ATTLIST vehicle op-status (on-time|late|early|out-of-service|special|none) #REQUIRED>
		<!ATTLIST vehicle comm-status (good|unknown) #REQUIRED>
		<!ATTLIST vehicle gps-status (good|bad|unknown) #REQUIRED>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT routeid (#PCDATA)>
		<!ELEMENT tripid (#PCDATA)>
		<!ELEMENT runid (#PCDATA)>
		<!ELEMENT destination (#PCDATA)>
		<!ELEMENT direction (#PCDATA)> <!-- I, O, or L -->
		<!ELEMENT laststop (#PCDATA)>
 		<!ELEMENT latitude (#PCDATA)>
		<!ELEMENT longitude (#PCDATA)>
		<!ELEMENT speed (#PCDATA)>
			<!ATTLIST speed units (mph|kph) "mph">
		<!ELEMENT heading (#PCDATA)>
]>

<vehicle-locations><report-generated timezone="-9">2017-06-27 10:33</report-generated><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>998</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17785</latitude><longitude>-149.81389</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>999</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>12345</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60201</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60202</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60203</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60204</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60205</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60206</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60207</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60208</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60209</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60210</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60211</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60212</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17775</latitude><longitude>-149.81215</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60213</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60214</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60215</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60216</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60217</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17745</latitude><longitude>-149.81354</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60218</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60219</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177517</latitude><longitude>-149.81256</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60220</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.21845</latitude><longitude>-149.8778</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60221</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178314</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60222</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1976</latitude><longitude>-149.74507</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60223</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.812</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60224</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60225</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17758</latitude><longitude>-149.81218</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60226</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17895</latitude><longitude>-149.8683</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60227</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.154034</latitude><longitude>-149.83435</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60228</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.180866</latitude><longitude>-149.79668</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60229</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177467</latitude><longitude>-149.81226</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60230</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.81302</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60231</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.210716</latitude><longitude>-149.73326</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60232</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177883</latitude><longitude>-149.81378</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60233</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177532</latitude><longitude>-149.81302</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60234</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60235</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177784</latitude><longitude>-149.81384</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60236</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17785</latitude><longitude>-149.81389</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60237</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178185</latitude><longitude>-149.8129</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60238</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177364</latitude><longitude>-149.81221</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60239</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.215614</latitude><longitude>-149.89667</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60240</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.134132</latitude><longitude>-149.86382</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60241</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.2324</latitude><longitude>-149.74362</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60242</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81409</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60243</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60244</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178185</latitude><longitude>-149.8128</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60245</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177917</latitude><longitude>-149.81377</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60246</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60247</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178017</latitude><longitude>-149.81245</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60248</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177532</latitude><longitude>-149.81256</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60249</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1774</latitude><longitude>-149.81226</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60250</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177567</latitude><longitude>-149.8125</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60260</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60261</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.81436</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60263</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177334</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60264</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.81218</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60265</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177334</latitude><longitude>-149.8125</longitude><speed>6</speed><heading>45</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60266</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60269</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1784</latitude><longitude>-149.81456</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="bad"><name>60273</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17735</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>58</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60274</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17835</latitude><longitude>-149.8129</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="bad"><name>60277</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178417</latitude><longitude>-149.81496</longitude><speed>2</speed><heading>172</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60281</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177467</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60282</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60288</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177483</latitude><longitude>-149.81245</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="good"><name>60289</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17745</latitude><longitude>-149.8127</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60292</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="bad"><name>60293</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1783</latitude><longitude>-149.81447</longitude><speed>4</speed><heading>270</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60294</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17755</latitude><longitude>-149.81221</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60297</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177364</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60999</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1769</latitude><longitude>-149.81406</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63001</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17835</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63002</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1774</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63003</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177315</latitude><longitude>-149.81357</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63004</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63005</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1779</latitude><longitude>-149.81377</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>Test</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name></name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60275</name><routeid>1</routeid><tripid>1010</tripid><runid>119</runid><destination>1 DIMOND CENTER</destination><direction>O</direction><laststop>PROVIDENCE and ALUMNI</laststop><latitude>61.188034</latitude><longitude>-149.83612</longitude><speed>38</speed><heading>266</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60251</name><routeid>1</routeid><tripid>910</tripid><runid>101</runid><destination>1 DIMOND CENTER</destination><direction>O</direction><laststop>DIMOND TRANSIT CENTER</laststop><latitude>61.1437</latitude><longitude>-149.8725</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60298</name><routeid>2</routeid><tripid>945</tripid><runid>123</runid><destination>2 DOWNTOWN</destination><direction>I</direction><laststop>A STREET and 36TH AVE</laststop><latitude>61.21555</latitude><longitude>-149.89577</longitude><speed>4</speed><heading>278</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60295</name><routeid>2</routeid><tripid>945</tripid><runid>121</runid><destination>2 DIMOND CENTER</destination><direction>O</direction><laststop>DIMOND TRANSIT CENTER</laststop><latitude>61.142517</latitude><longitude>-149.8719</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60284</name><routeid>3</routeid><tripid>953</tripid><runid>132</runid><destination>3C CENTENNIAL</destination><direction>O</direction><laststop>PATTERSON and NORTHERN LIGHTS</laststop><latitude>61.19775</latitude><longitude>-149.74507</longitude><speed>15</speed><heading>358</heading></vehicle><vehicle op-status="on-time" comm-status="bad" gps-status="bad"><name>60268</name><routeid>3</routeid><tripid>934</tripid><runid>137</runid><destination>3N DOWNTOWN</destination><direction>I</direction><laststop>I STREET and 13TH AVENUE NNE: 1159</laststop><latitude>61.215733</latitude><longitude>-149.89548</longitude><speed>13</speed><heading>176</heading></vehicle><vehicle op-status="late" comm-status="good" gps-status="good"><name>60259</name><routeid>3</routeid><tripid>1023</tripid><runid>103</runid><destination>3N MULDOON</destination><direction>O</direction><laststop>C STREET and 7TH AVENUE SSW</laststop><latitude>61.213585</latitude><longitude>-149.8983</longitude><speed>24</speed><heading>272</heading></vehicle><vehicle op-status="late" comm-status="good" gps-status="good"><name>60254</name><routeid>3</routeid><tripid>954</tripid><runid>131</runid><destination>3C DOWNTOWN</destination><direction>I</direction><laststop>PROVIDENCE and PROVIDENCE HOSPITAL</laststop><latitude>61.185764</latitude><longitude>-149.82317</longitude><speed>4</speed><heading>358</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60258</name><routeid>7</routeid><tripid>959</tripid><runid>114</runid><destination>7J DOWNTOWN</destination><direction>I</direction><laststop>SPENARD and NORTHERN LIGHTS</laststop><latitude>61.199165</latitude><longitude>-149.91293</longitude><speed>33</speed><heading>358</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60262</name><routeid>7</routeid><tripid>1015</tripid><runid>124</runid><destination>7J DIMOND CENTER</destination><direction>O</direction><laststop>C STREET and 7TH AVENUE SSW</laststop><latitude>61.193085</latitude><longitude>-149.90552</longitude><speed>2</speed><heading>178</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60283</name><routeid>7</routeid><tripid>945</tripid><runid>120</runid><destination>7A DIMOND CENTER</destination><direction>O</direction><laststop>DIMOND and ARCTIC ESE: 0683</laststop><latitude>61.144516</latitude><longitude>-149.88518</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60252</name><routeid>7</routeid><tripid>1022</tripid><runid>102</runid><destination>7A DOWNTOWN</destination><direction>I</direction><laststop>NORTHWOOD and 80TH AVENUE SSE: 3540</laststop><latitude>61.150932</latitude><longitude>-149.92189</longitude><speed>11</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60256</name><routeid>8</routeid><tripid>1017</tripid><runid>118</runid><destination>8 DOWNTOWN</destination><direction>I</direction><laststop>LIONHEART and FIREOVED DR WNW: 0817</laststop><latitude>61.220165</latitude><longitude>-149.78668</longitude><speed>13</speed><heading>270</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60300</name><routeid>8</routeid><tripid>1031</tripid><runid>104</runid><destination>8 MULDOON</destination><direction>O</direction><laststop>6TH AVENUE and C STREET ESE</laststop><latitude>61.216534</latitude><longitude>-149.88567</longitude><speed>15</speed><heading>84</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60257</name><routeid>9</routeid><tripid>1019</tripid><runid>112</runid><destination>9 DIMOND CENTER</destination><direction>O</direction><laststop>ARCTIC and BENSON</laststop><latitude>61.173767</latitude><longitude>-149.89809</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="late" comm-status="good" gps-status="good"><name>60291</name><routeid>9</routeid><tripid>1013</tripid><runid>141</runid><destination>9 DOWNTOWN</destination><direction>I</direction><laststop>ARCTIC and 34TH AVENUE NNE</laststop><latitude>61.1901</latitude><longitude>-149.89781</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="OOS Inactive" gps-status="bad"><name>60280</name><routeid>9</routeid><tripid>943</tripid><runid>129</runid><destination>9 DOWNTOWN</destination><direction>I</direction><laststop>DOWNTOWN TRANSIT CENTER</laststop><latitude>61.21555</latitude><longitude>-149.89644</longitude><speed>8</speed><heading>270</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60296</name><routeid>13</routeid><tripid>1005</tripid><runid>115</runid><destination>13 MULDOON</destination><direction>O</direction><laststop>ALASKA REGIONAL HOSPITAL</laststop><latitude>61.209</latitude><longitude>-149.82335</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60302</name><routeid>13</routeid><tripid>1015</tripid><runid>109</runid><destination>13 DOWNTOWN</destination><direction>I</direction><laststop>AMBASSADOR and ELMORE ENE</laststop><latitude>61.185883</latitude><longitude>-149.80965</longitude><speed>24</speed><heading>328</heading></vehicle><vehicle op-status="late" comm-status="good" gps-status="good"><name>60299</name><routeid>15</routeid><tripid>1005</tripid><runid>113</runid><destination>15 MULDOON</destination><dire