<?xml version="1.0"?>
<!DOCTYPE vehicle-locations [
<!ELEMENT vehicle-locations (report-generated, vehicle*)>
	<!ELEMENT report-generated (#PCDATA)>
		<!-- timezone is an integer between -12 and 12 inclusive. -->
       <!-- the timezone is reference to GMT and is -5 for Acadia. -->
		<!ATTLIST report-generated timezone CDATA #REQUIRED>
	<!ELEMENT vehicle (name, routeid, tripid, runid*, destination*, direction, laststop, latitude, longitude, speed, heading)>
		<!ATTLIST vehicle op-status (on-time|late|early|out-of-service|special|none) #REQUIRED>
		<!ATTLIST vehicle comm-status (good|unknown) #REQUIRED>
		<!ATTLIST vehicle gps-status (good|bad|unknown) #REQUIRED>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT routeid (#PCDATA)>
		<!ELEMENT tripid (#PCDATA)>
		<!ELEMENT runid (#PCDATA)>
		<!ELEMENT destination (#PCDATA)>
		<!ELEMENT direction (#PCDATA)> <!-- I, O, or L -->
		<!ELEMENT laststop (#PCDATA)>
 		<!ELEMENT latitude (#PCDATA)>
		<!ELEMENT longitude (#PCDATA)>
		<!ELEMENT speed (#PCDATA)>
			<!ATTLIST speed units (mph|kph) "mph">
		<!ELEMENT heading (#PCDATA)>
]>

<vehicle-locations><report-generated timezone="-9">2017-07-02 14:48</report-generated><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>998</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17785</latitude><longitude>-149.81389</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>999</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>12345</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60201</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60202</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60203</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60204</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60205</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60206</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60207</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60208</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60209</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60210</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60211</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60212</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17775</latitude><longitude>-149.81215</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60213</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60214</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60215</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60216</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60217</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17745</latitude><longitude>-149.81354</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60218</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60219</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.8143</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60220</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.21845</latitude><longitude>-149.8778</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60222</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1976</latitude><longitude>-149.74507</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60223</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.812</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60224</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60225</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17758</latitude><longitude>-149.81218</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60226</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17895</latitude><longitude>-149.8683</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60227</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.154034</latitude><longitude>-149.83435</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60228</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.180866</latitude><longitude>-149.79668</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60229</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177467</latitude><longitude>-149.81226</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60230</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.81302</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60231</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.210716</latitude><longitude>-149.73326</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60232</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177883</latitude><longitude>-149.81378</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60233</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177765</latitude><longitude>-149.81284</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60234</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60235</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177784</latitude><longitude>-149.81384</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60236</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17785</latitude><longitude>-149.81389</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60237</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178185</latitude><longitude>-149.81287</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60238</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177364</latitude><longitude>-149.81221</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60239</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.215614</latitude><longitude>-149.89667</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60240</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177567</latitude><longitude>-149.81215</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60241</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.2324</latitude><longitude>-149.74362</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60242</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81409</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60243</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60244</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178185</latitude><longitude>-149.8128</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60245</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177917</latitude><longitude>-149.81377</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60246</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60247</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17758</latitude><longitude>-149.81287</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60248</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177532</latitude><longitude>-149.81256</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60249</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1774</latitude><longitude>-149.81226</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60250</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177567</latitude><longitude>-149.8125</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60266</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60267</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177334</latitude><longitude>-149.8137</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60268</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1784</latitude><longitude>-149.81401</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60269</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178185</latitude><longitude>-149.81474</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60270</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178333</latitude><longitude>-149.81436</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60271</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60272</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17815</latitude><longitude>-149.81294</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60273</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178383</latitude><longitude>-149.81316</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60274</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177334</latitude><longitude>-149.81273</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60275</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178165</latitude><longitude>-149.81305</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60276</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178314</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60277</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178333</latitude><longitude>-149.81444</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60278</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17835</latitude><longitude>-149.8145</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60254</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177467</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60255</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17735</latitude><longitude>-149.81366</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60252</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81221</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60282</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60284</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.203484</latitude><longitude>-149.71385</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60292</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60293</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178185</latitude><longitude>-149.8118</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60294</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178333</latitude><longitude>-149.81436</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60295</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178333</latitude><longitude>-149.81436</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60296</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1776</latitude><longitude>-149.81284</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60297</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17835</latitude><longitude>-149.8129</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60298</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60299</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177765</latitude><longitude>-149.8129</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60300</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17835</latitude><longitude>-149.81427</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60301</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178234</latitude><longitude>-149.8145</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60302</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178333</latitude><longitude>-149.8143</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60999</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1769</latitude><longitude>-149.81406</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63001</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17835</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63002</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1774</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63003</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177315</latitude><longitude>-149.81357</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63004</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63005</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1779</latitude><longitude>-149.81377</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>Test</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name></name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="OOS Inactive" gps-status="bad"><name>60287</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17745</latitude><longitude>-149.81221</longitude><speed>2</speed><heading>66</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60288</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177483</latitude><longitude>-149.81245</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60289</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17745</latitude><longitude>-149.81226</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60260</name><routeid>1</routeid><tripid>1447</tripid><runid>320</runid><destination>1 MULDOON</destination><direction>I</direction><laststop></laststop><latitude>61.142715</latitude><longitude>-149.8719</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="late" comm-status="good" gps-status="good"><name>60263</name><routeid>1</routeid><tripid>1408</tripid><runid>317</runid><destination>1 DIMOND CENTER</destination><direction>O</direction><laststop>88TH AVENUE and OLD SEWARD WNW</laststop><latitude>61.141968</latitude><longitude>-149.87193</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60259</name><routeid>3</routeid><tripid>1410</tripid><runid>302</runid><destination>3N CENTENNIAL</destination><direction>O</direction><laststop>NORTHERN LIGHTS and BONIFACE</laststop><latitude>61.20725</latitude><longitude>-149.77007</longitude><speed>17</speed><heading>358</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60290</name><routeid>3</routeid><tripid>1407</tripid><runid>304</runid><destination>3C DOWNTOWN</destination><direction>I</direction><laststop>NORTHERN LIGHTS and SPENARD WNW: 0409</laststop><latitude>61.19535</latitude><longitude>-149.91264</longitude><speed>2</speed><heading>268</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60291</name><routeid>7</routeid><tripid>1440</tripid><runid>309</runid><destination>7A DOWNTOWN</destination><direction>I</direction><laststop>DIMOND TRANSIT CENTER</laststop><latitude>61.144817</latitude><longitude>-149.87787</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60286</name><routeid>7</routeid><tripid>1428</tripid><runid>307</runid><destination>7A DIMOND CENTER</destination><direction>O</direction><laststop>SPENARD and WISCONSIN</laststop><latitude>61.178432</latitude><longitude>-149.93974</longitude><speed>17</speed><heading>202</heading></vehicle><vehicle op-status="late" comm-status="good" gps-status="good"><name>60261</name><routeid>8</routeid><tripid>1426</tripid><runid>303</runid><destination>8 DOWNTOWN</destination><direction>I</direction><laststop>4TH AVENUE and PINE WNW: 0820</laststop><latitude>61.217815</latitude><longitude>-149.80466</longitude><speed>29</speed><heading>178</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="bad"><name>60251</name><routeid>8</routeid><tripid>1445</tripid><runid>319</runid><destination>8 MULDOON</destination><direction>O</direction><laststop></laststop><latitude>61.215485</latitude><longitude>-149.89618</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60258</name><routeid>9</routeid><tripid>1431</tripid><runid>306</runid><destination>9 DOWNTOWN</destination><direction>I</direction><laststop>ARCTIC and CHUGACH WAY NNE: 0711</laststop><latitude>61.193466</latitude><longitude>-149.89784</longitude><speed>17</speed><heading>354</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60262</name><routeid>13</routeid><tripid>1411</tripid><runid>305</runid><destination>13 MULDOON</destination><direction>O<