<?xml version="1.0"?>
<!DOCTYPE vehicle-locations [
<!ELEMENT vehicle-locations (report-generated, vehicle*)>
	<!ELEMENT report-generated (#PCDATA)>
		<!-- timezone is an integer between -12 and 12 inclusive. -->
       <!-- the timezone is reference to GMT and is -5 for Acadia. -->
		<!ATTLIST report-generated timezone CDATA #REQUIRED>
	<!ELEMENT vehicle (name, routeid, tripid, runid*, destination*, direction, laststop, latitude, longitude, speed, heading)>
		<!ATTLIST vehicle op-status (on-time|late|early|out-of-service|special|none) #REQUIRED>
		<!ATTLIST vehicle comm-status (good|unknown) #REQUIRED>
		<!ATTLIST vehicle gps-status (good|bad|unknown) #REQUIRED>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT routeid (#PCDATA)>
		<!ELEMENT tripid (#PCDATA)>
		<!ELEMENT runid (#PCDATA)>
		<!ELEMENT destination (#PCDATA)>
		<!ELEMENT direction (#PCDATA)> <!-- I, O, or L -->
		<!ELEMENT laststop (#PCDATA)>
 		<!ELEMENT latitude (#PCDATA)>
		<!ELEMENT longitude (#PCDATA)>
		<!ELEMENT speed (#PCDATA)>
			<!ATTLIST speed units (mph|kph) "mph">
		<!ELEMENT heading (#PCDATA)>
]>

<vehicle-locations><report-generated timezone="-9">2017-06-27 09:42</report-generated><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>998</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17785</latitude><longitude>-149.81389</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>999</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>12345</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60201</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60202</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60203</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60204</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60205</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60206</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60207</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60208</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60209</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60210</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60211</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60212</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17775</latitude><longitude>-149.81215</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60213</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60214</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60215</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60216</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60217</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17745</latitude><longitude>-149.81354</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60218</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60219</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177517</latitude><longitude>-149.81256</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60220</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.21845</latitude><longitude>-149.8778</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60221</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178314</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60222</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1976</latitude><longitude>-149.74507</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60223</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.812</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60224</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60225</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17758</latitude><longitude>-149.81218</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60226</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17895</latitude><longitude>-149.8683</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60227</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.154034</latitude><longitude>-149.83435</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60228</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.180866</latitude><longitude>-149.79668</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60229</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177467</latitude><longitude>-149.81226</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60230</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.81302</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60231</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.210716</latitude><longitude>-149.73326</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60232</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177883</latitude><longitude>-149.81378</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60233</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177532</latitude><longitude>-149.81302</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60234</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60235</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177784</latitude><longitude>-149.81384</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60236</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17785</latitude><longitude>-149.81389</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60237</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178185</latitude><longitude>-149.8129</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60238</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177364</latitude><longitude>-149.81221</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60239</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.215614</latitude><longitude>-149.89667</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60240</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.134132</latitude><longitude>-149.86382</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60241</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.2324</latitude><longitude>-149.74362</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60242</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81409</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60243</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60244</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178185</latitude><longitude>-149.8128</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60245</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177917</latitude><longitude>-149.81377</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60246</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60247</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178017</latitude><longitude>-149.81245</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60248</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177532</latitude><longitude>-149.81256</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60249</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1774</latitude><longitude>-149.81226</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60250</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177567</latitude><longitude>-149.8125</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60260</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60261</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.81436</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60263</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177334</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60264</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.81218</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60266</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60269</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1784</latitude><longitude>-149.81456</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="bad"><name>60273</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17735</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>58</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60274</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17835</latitude><longitude>-149.8129</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60281</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177467</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60282</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1775</latitude><longitude>-149.81232</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60288</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177483</latitude><longitude>-149.81245</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="good"><name>60289</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17745</latitude><longitude>-149.8127</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60292</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177383</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="bad"><name>60293</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1783</latitude><longitude>-149.81447</longitude><speed>4</speed><heading>270</heading></vehicle><vehicle op-status="none" comm-status="good" gps-status="bad"><name>60294</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17755</latitude><longitude>-149.81221</longitude><speed>2</speed><heading>16</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60297</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177364</latitude><longitude>-149.81229</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>60999</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1769</latitude><longitude>-149.81406</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63001</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.17835</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63002</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1774</latitude><longitude>-149.81238</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63003</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177315</latitude><longitude>-149.81357</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63004</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.178368</latitude><longitude>-149.8144</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>63005</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.1779</latitude><longitude>-149.81377</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name>Test</name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>0.0</latitude><longitude>0.0</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="none" comm-status="OOS Inactive" gps-status="bad"><name></name><routeid>0</routeid><tripid>0</tripid><direction></direction><laststop></laststop><latitude>61.177418</latitude><longitude>-149.81235</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60278</name><routeid>1</routeid><tripid>940</tripid><runid>128</runid><destination>1 MULDOON</destination><direction>I</direction><laststop>DIMOND TRANSIT CENTER</laststop><latitude>61.144432</latitude><longitude>-149.87144</longitude><speed>6</speed><heading>358</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60251</name><routeid>1</routeid><tripid>910</tripid><runid>101</runid><destination>1 DIMOND CENTER</destination><direction>O</direction><laststop>LAKE OTIS and DOWLING</laststop><latitude>61.16485</latitude><longitude>-149.83801</longitude><speed>40</speed><heading>162</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60298</name><routeid>2</routeid><tripid>945</tripid><runid>123</runid><destination>2 DOWNTOWN</destination><direction>I</direction><laststop></laststop><latitude>61.14265</latitude><longitude>-149.87196</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60299</name><routeid>3</routeid><tripid>854</tripid><runid>113</runid><destination>3C DOWNTOWN</destination><direction>I</direction><laststop>NORTHERN LIGHTS and ARCTIC WNW: 0408</laststop><latitude>61.1953</latitude><longitude>-149.89874</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60268</name><routeid>3</routeid><tripid>934</tripid><runid>137</runid><destination>3N DOWNTOWN</destination><direction>I</direction><laststop>NUNAKA and DEBARR</laststop><latitude>61.19885</latitude><longitude>-149.7777</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60254</name><routeid>3</routeid><tripid>853</tripid><runid>131</runid><destination>3C CENTENNIAL</destination><direction>O</direction><laststop>MULDOON and DEBARR EAST</laststop><latitude>61.21875</latitude><longitude>-149.73335</longitude><speed>26</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60256</name><routeid>3</routeid><tripid>923</tripid><runid>118</runid><destination>3N MULDOON</destination><direction>O</direction><laststop>BENSON and DENALI ESE</laststop><latitude>61.193333</latitude><longitude>-149.8751</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60262</name><routeid>7</routeid><tripid>923</tripid><runid>124</runid><destination>7A DOWNTOWN</destination><direction>I</direction><laststop>STRAWBERRY and LOTUS WNW: 3575</laststop><latitude>61.17415</latitude><longitude>-149.96545</longitude><speed>29</speed><heading>268</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60291</name><routeid>7</routeid><tripid>920</tripid><runid>117</runid><destination>7J DIMOND CENTER</destination><direction>O</direction><laststop>SPENARD and TURNAGAIN BLVD WNW</laststop><latitude>61.181484</latitude><longitude>-149.93562</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60283</name><routeid>7</routeid><tripid>945</tripid><runid>120</runid><destination>7A DIMOND CENTER</destination><direction>O</direction><laststop></laststop><latitude>61.21655</latitude><longitude>-149.8974</longitude><speed>11</speed><heading>74</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60253</name><routeid>8</routeid><tripid>917</tripid><runid>108</runid><destination>8 DOWNTOWN</destination><direction>I</direction><laststop>PENLAND PKWY and PAUL LALONE N: 0514</laststop><latitude>61.215515</latitude><longitude>-149.8221</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60302</name><routeid>8</routeid><tripid>931</tripid><runid>109</runid><destination>8 MULDOON</destination><direction>O</direction><laststop>4TH AVENUE and KARLUK ESE: 1258</laststop><latitude>61.22325</latitude><longitude>-149.82841</longitude><speed>38</speed><heading>38</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60258</name><routeid>9</routeid><tripid>919</tripid><runid>114</runid><destination>9 DIMOND CENTER</destination><direction>O</direction><laststop>DIMOND and C STREET ESE: 0684</laststop><latitude>61.144566</latitude><longitude>-149.87337</longitude><speed>33</speed><heading>90</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60280</name><routeid>9</routeid><tripid>943</tripid><runid>129</runid><destination>9 DOWNTOWN</destination><direction>I</direction><laststop></laststop><latitude>61.142414</latitude><longitude>-149.87187</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60252</name><routeid>9</routeid><tripid>913</tripid><runid>102</runid><destination>9 DOWNTOWN</destination><direction>I</direction><laststop>DOWNTOWN TRANSIT CENTER</laststop><latitude>61.215633</latitude><longitude>-149.8966</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="late" comm-status="good" gps-status="good"><name>60275</name><routeid>13</routeid><tripid>905</tripid><runid>119</runid><destination>13 MULDOON</destination><direction>O</direction><laststop>ALASKA REGIONAL HOSPITAL</laststop><latitude>61.19678</latitude><longitude>-149.83847</longitude><speed>38</speed><heading>180</heading></vehicle><vehicle op-status="late" comm-status="good" gps-status="good"><name>60259</name><routeid>13</routeid><tripid>915</tripid><runid>103</runid><destination>13 DOWNTOWN</destination><direction>I</direction><laststop>PROVIDENCE and ALUMNI</laststop><latitude>61.18765</latitude><longitude>-149.8291</longitude><speed>13</speed><heading>0</heading></vehicle><vehicle op-status="out-of-service" comm-status="OOS Inactive" gps-status="bad"><name>60295</name><routeid>13</routeid><tripid>815</tripid><runid>121</runid><destination>13 DOWNTOWN</destination><direction>I</direction><laststop>DOWNTOWN TRANSIT CENTER</laststop><latitude>61.21545</latitude><longitude>-149.89609</longitude><speed>4</speed><heading>272</heading></vehicle><vehicle op-status="out-of-service" comm-status="OOS Inactive" gps-status="bad"><name>60270</name><routeid>15</routeid><tripid>842</tripid><runid>136</runid><destination>15 DOWNTOWN</destination><direction>I</direction><laststop>DOWNTOWN TRANSIT CENTER</laststop><latitude>61.215515</latitude><longitude>-149.89618</longitude><speed>2</speed><heading>270</heading></vehicle><vehicle op-status="out-of-service" comm-status="good" gps-status="good"><name>60279</name><routeid>15</routeid><tripid>942</tripid><runid>116</runid><destination>15 DOWNTOWN</destination><direction>I</direction><laststop></laststop><latitude>61.209816</latitude><longitude>-149.73512</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60287</name><routeid>15</routeid><tripid>935</tripid><runid>138</runid><destination>15 MULDOON</destination><direction>O</direction><laststop>15TH AVENUE and EAGLE ESE: 3556</laststop><latitude>61.20765</latitude><longitude>-149.87462</longitude><speed>0</speed><heading>0</heading></vehicle><vehicle op-status="on-time" comm-status="good" gps-status="good"><name>60272</name><routeid>36</routeid><tripid>910</tripid