<?xml version="1.0"?><!DOCTYPE routestops [	<!ELEMENT routestops (routestop*)>		<!ELEMENT routestop (route_number, stop_id, sort_order)>			<!ELEMENT route_number (#PCDATA)>			<!ELEMENT stop_id (#PCDATA)> 			<!ELEMENT sort_order (#PCDATA)> ]>
<routestops><routestop><route_number>1</route_number><stop_id>1437</stop_id><sort_order>43</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1438</stop_id><sort_order>116</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1439</stop_id><sort_order>117</sort_order></routestop><routestop><route_number>3</route_number><stop_id>1440</stop_id><sort_order>151</sort_order></routestop><routestop><route_number>3</route_number><stop_id>1441</stop_id><sort_order>152</sort_order></routestop><routestop><route_number>3</route_number><stop_id>1442</stop_id><sort_order>149</sort_order></routestop><routestop><route_number>3</route_number><stop_id>1443</stop_id><sort_order>150</sort_order></routestop><routestop><route_number>3</route_number><stop_id>1444</stop_id><sort_order>82</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1445</stop_id><sort_order>139</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1446</stop_id><sort_order>77</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1447</stop_id><sort_order>76</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1448</stop_id><sort_order>78</sort_order></routestop><routestop><route_number>8</route_number><stop_id>1449</stop_id><sort_order>50</sort_order></routestop><routestop><route_number>8</route_number><stop_id>1450</stop_id><sort_order>53</sort_order></routestop><routestop><route_number>9</route_number><stop_id>1451</stop_id><sort_order>56</sort_order></routestop><routestop><route_number>13</route_number><stop_id>1452</stop_id><sort_order>74</sort_order></routestop><routestop><route_number>13</route_number><stop_id>1453</stop_id><sort_order>73</sort_order></routestop><routestop><route_number>3</route_number><stop_id>1453</stop_id><sort_order>84</sort_order></routestop><routestop><route_number>13</route_number><stop_id>1454</stop_id><sort_order>12</sort_order></routestop><routestop><route_number>14</route_number><stop_id>1455</stop_id><sort_order>12</sort_order></routestop><routestop><route_number>14</route_number><stop_id>1456</stop_id><sort_order>13</sort_order></routestop><routestop><route_number>13</route_number><stop_id>1457</stop_id><sort_order>13</sort_order></routestop><routestop><route_number>15</route_number><stop_id>1457</stop_id><sort_order>63</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1458</stop_id><sort_order>13</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1459</stop_id><sort_order>14</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1459</stop_id><sort_order>17</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1460</stop_id><sort_order>15</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1461</stop_id><sort_order>16</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1462</stop_id><sort_order>17</sort_order></routestop><routestop><route_number>45</route_number><stop_id>1463</stop_id><sort_order>10</sort_order></routestop><routestop><route_number>45</route_number><stop_id>1464</stop_id><sort_order>114</sort_order></routestop><routestop><route_number>15</route_number><stop_id>1464</stop_id><sort_order>10</sort_order></routestop><routestop><route_number>8</route_number><stop_id>1464</stop_id><sort_order>108</sort_order></routestop><routestop><route_number>45</route_number><stop_id>1465</stop_id><sort_order>115</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1467</stop_id><sort_order>123</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1468</stop_id><sort_order>124</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1469</stop_id><sort_order>128</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1470</stop_id><sort_order>1</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1471</stop_id><sort_order>110</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1473</stop_id><sort_order>111</sort_order></routestop><routestop><route_number>8</route_number><stop_id>1473</stop_id><sort_order>92</sort_order></routestop><routestop><route_number>3</route_number><stop_id>1473</stop_id><sort_order>153</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1473</stop_id><sort_order>108</sort_order></routestop><routestop><route_number>8</route_number><stop_id>1474</stop_id><sort_order>90</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1474</stop_id><sort_order>101</sort_order></routestop><routestop><route_number>13</route_number><stop_id>1474</stop_id><sort_order>128</sort_order></routestop><routestop><route_number>13</route_number><stop_id>1477</stop_id><sort_order>129</sort_order></routestop><routestop><route_number>15</route_number><stop_id>1477</stop_id><sort_order>8</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1477</stop_id><sort_order>115</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1477</stop_id><sort_order>102</sort_order></routestop><routestop><route_number>45</route_number><stop_id>1477</stop_id><sort_order>97</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1477</stop_id><sort_order>119</sort_order></routestop><routestop><route_number>8</route_number><stop_id>1477</stop_id><sort_order>101</sort_order></routestop><routestop><route_number>9</route_number><stop_id>1477</stop_id><sort_order>5</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1477</stop_id><sort_order>144</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1477</stop_id><sort_order>114</sort_order></routestop><routestop><route_number>3</route_number><stop_id>1477</stop_id><sort_order>143</sort_order></routestop><routestop><route_number>14</route_number><stop_id>1477</stop_id><sort_order>8</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1478</stop_id><sort_order>57</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1478</stop_id><sort_order>102</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1478</stop_id><sort_order>87</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1479</stop_id><sort_order>86</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1479</stop_id><sort_order>101</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1479</stop_id><sort_order>132</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1481</stop_id><sort_order>55</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1481</stop_id><sort_order>56</sort_order></routestop><routestop><route_number>45</route_number><stop_id>1481</stop_id><sort_order>95</sort_order></routestop><routestop><route_number>13</route_number><stop_id>1481</stop_id><sort_order>112</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1482</stop_id><sort_order>97</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1487</stop_id><sort_order>136</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1490</stop_id><sort_order>135</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1492</stop_id><sort_order>85</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1494</stop_id><sort_order>63</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1494</stop_id><sort_order>99</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1494</stop_id><sort_order>102</sort_order></routestop><routestop><route_number>9</route_number><stop_id>1494</stop_id><sort_order>53</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1494</stop_id><sort_order>96</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1498</stop_id><sort_order>80</sort_order></routestop><routestop><route_number>45</route_number><stop_id>1498</stop_id><sort_order>79</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1498</stop_id><sort_order>66</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1498</stop_id><sort_order>93</sort_order></routestop><routestop><route_number>9</route_number><stop_id>1498</stop_id><sort_order>33</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1498</stop_id><sort_order>96</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1498</stop_id><sort_order>70</sort_order></routestop><routestop><route_number>3</route_number><stop_id>1498</stop_id><sort_order>112</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1498</stop_id><sort_order>109</sort_order></routestop><routestop><route_number>14</route_number><stop_id>1498</stop_id><sort_order>2</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1499</stop_id><sort_order>110</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1499</stop_id><sort_order>71</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1499</stop_id><sort_order>67</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1500</stop_id><sort_order>79</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1500</stop_id><sort_order>85</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1500</stop_id><sort_order>111</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1501</stop_id><sort_order>112</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1501</stop_id><sort_order>86</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1501</stop_id><sort_order>80</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1502</stop_id><sort_order>81</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1502</stop_id><sort_order>87</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1502</stop_id><sort_order>91</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1503</stop_id><sort_order>114</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1503</stop_id><sort_order>55</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1503</stop_id><sort_order>82</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1504</stop_id><sort_order>70</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1504</stop_id><sort_order>75</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1504</stop_id><sort_order>100</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1505</stop_id><sort_order>101</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1505</stop_id><sort_order>76</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1505</stop_id><sort_order>71</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1506</stop_id><sort_order>64</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1506</stop_id><sort_order>63</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1506</stop_id><sort_order>81</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1507</stop_id><sort_order>80</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1507</stop_id><sort_order>62</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1507</stop_id><sort_order>63</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1508</stop_id><sort_order>56</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1508</stop_id><sort_order>65</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1508</stop_id><sort_order>83</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1509</stop_id><sort_order>82</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1509</stop_id><sort_order>64</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1509</stop_id><sort_order>55</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1510</stop_id><sort_order>58</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1510</stop_id><sort_order>67</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1510</stop_id><sort_order>51</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1511</stop_id><sort_order>63</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1511</stop_id><sort_order>66</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1511</stop_id><sort_order>57</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1512</stop_id><sort_order>49</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1512</stop_id><sort_order>69</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1512</stop_id><sort_order>87</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1513</stop_id><sort_order>86</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1513</stop_id><sort_order>68</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1513</stop_id><sort_order>59</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1514</stop_id><sort_order>53</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1514</stop_id><sort_order>61</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1514</stop_id><sort_order>77</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1515</stop_id><sort_order>76</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1515</stop_id><sort_order>60</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1515</stop_id><sort_order>52</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1517</stop_id><sort_order>59</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1517</stop_id><sort_order>51</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1518</stop_id><sort_order>52</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1518</stop_id><sort_order>49</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1519</stop_id><sort_order>57</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1519</stop_id><sort_order>49</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1520</stop_id><sort_order>50</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1520</stop_id><sort_order>58</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1521</stop_id><sort_order>48</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1521</stop_id><sort_order>42</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1522</stop_id><sort_order>48</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1522</stop_id><sort_order>56</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1523</stop_id><sort_order>53</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1523</stop_id><sort_order>45</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1524</stop_id><sort_order>46</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1524</stop_id><sort_order>54</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1525</stop_id><sort_order>51</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1525</stop_id><sort_order>41</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1526</stop_id><sort_order>44</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1526</stop_id><sort_order>47</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1527</stop_id><sort_order>46</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1527</stop_id><sort_order>39</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1528</stop_id><sort_order>38</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1528</stop_id><sort_order>45</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1529</stop_id><sort_order>44</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1529</stop_id><sort_order>37</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1530</stop_id><sort_order>36</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1530</stop_id><sort_order>43</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1531</stop_id><sort_order>42</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1531</stop_id><sort_order>35</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1532</stop_id><sort_order>23</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1532</stop_id><sort_order>41</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1533</stop_id><sort_order>40</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1534</stop_id><sort_order>39</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1535</stop_id><sort_order>28</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1536</stop_id><sort_order>37</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1537</stop_id><sort_order>3</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1538</stop_id><sort_order>25</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1539</stop_id><sort_order>26</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1540</stop_id><sort_order>27</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1541</stop_id><sort_order>20</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1541</stop_id><sort_order>27</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1542</stop_id><sort_order>28</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1542</stop_id><sort_order>21</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1543</stop_id><sort_order>22</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1543</stop_id><sort_order>29</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1544</stop_id><sort_order>30</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1544</stop_id><sort_order>14</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1545</stop_id><sort_order>18</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1545</stop_id><sort_order>23</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1546</stop_id><sort_order>17</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1546</stop_id><sort_order>19</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1547</stop_id><sort_order>11</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1547</stop_id><sort_order>16</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1548</stop_id><sort_order>15</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1548</stop_id><sort_order>10</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1549</stop_id><sort_order>13</sort_order></routestop><routestop><route_number>60</route_number><stop_id>1549</stop_id><sort_order>4</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1550</stop_id><sort_order>12</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1551</stop_id><sort_order>7</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1552</stop_id><sort_order>6</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1553</stop_id><sort_order>9</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1554</stop_id><sort_order>8</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1555</stop_id><sort_order>5</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1556</stop_id><sort_order>4</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1557</stop_id><sort_order>105</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1558</stop_id><sort_order>106</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1558</stop_id><sort_order>91</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1559</stop_id><sort_order>88</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1559</stop_id><sort_order>103</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1560</stop_id><sort_order>104</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1560</stop_id><sort_order>65</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1561</stop_id><sort_order>69</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1561</stop_id><sort_order>109</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1562</stop_id><sort_order>110</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1562</stop_id><sort_order>95</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1563</stop_id><sort_order>92</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1563</stop_id><sort_order>107</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1564</stop_id><sort_order>108</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1564</stop_id><sort_order>68</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1565</stop_id><sort_order>98</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1565</stop_id><sort_order>111</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1566</stop_id><sort_order>112</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1566</stop_id><sort_order>99</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1567</stop_id><sort_order>67</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1567</stop_id><sort_order>91</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1568</stop_id><sort_order>90</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1568</stop_id><sort_order>66</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1569</stop_id><sort_order>53</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1569</stop_id><sort_order>89</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1570</stop_id><sort_order>88</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1570</stop_id><sort_order>64</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1571</stop_id><sort_order>70</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1571</stop_id><sort_order>95</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1572</stop_id><sort_order>94</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1572</stop_id><sort_order>55</sort_order></routestop><routestop><route_number>1</route_number><stop_id>1573</stop_id><sort_order>54</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1573</stop_id><sort_order>93</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1574</stop_id><sort_order>92</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1574</stop_id><sort_order>97</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1574</stop_id><sort_order>48</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1576</stop_id><sort_order>123</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1576</stop_id><sort_order>100</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1576</stop_id><sort_order>97</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1577</stop_id><sort_order>96</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1577</stop_id><sort_order>99</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1577</stop_id><sort_order>122</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1578</stop_id><sort_order>106</sort_order></routestop><routestop><route_number>36</route_number><stop_id>1578</stop_id><sort_order>90</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1578</stop_id><sort_order>80</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1579</stop_id><sort_order>79</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1579</stop_id><sort_order>74</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1579</stop_id><sort_order>62</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1580</stop_id><sort_order>61</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1580</stop_id><sort_order>73</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1580</stop_id><sort_order>78</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1581</stop_id><sort_order>77</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1581</stop_id><sort_order>72</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1581</stop_id><sort_order>60</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1582</stop_id><sort_order>65</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1582</stop_id><sort_order>78</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1582</stop_id><sort_order>84</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1583</stop_id><sort_order>83</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1583</stop_id><sort_order>77</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1583</stop_id><sort_order>33</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1584</stop_id><sort_order>108</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1584</stop_id><sort_order>76</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1584</stop_id><sort_order>82</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1585</stop_id><sort_order>81</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1585</stop_id><sort_order>75</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1585</stop_id><sort_order>107</sort_order></routestop><routestop><route_number>10</route_number><stop_id>1586</stop_id><sort_order>99</sort_order></routestop><routestop><route_number>75</route_number><stop_id>1586</stop_id><sort_order>69</sort_order></routestop><routestop><route_number>2</route_number><stop_id>1586</stop_id><sort_order>74</sort_order></routestop><routestop><route_number>3</route_number><stop_id>1587</stop_id><sort_order>105</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1587</stop_id><sort_order>99</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1588</stop_id><sort_order>44</sort_order></routestop><routestop><route_number>3</route_number><stop_id>1588</stop_id><sort_order>5</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1589</stop_id><sort_order>45</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1590</stop_id><sort_order>7</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1591</stop_id><sort_order>43</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1592</stop_id><sort_order>12</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1593</stop_id><sort_order>49</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1594</stop_id><sort_order>11</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1595</stop_id><sort_order>47</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1596</stop_id><sort_order>39</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1597</stop_id><sort_order>40</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1598</stop_id><sort_order>61</sort_order></routestop><routestop><route_number>7</route_number><stop_id>1599</stop_id><sort_order>60</sort_order></routestop><routestop><route_number>7